### ISSUE TITLE
Rare use of switch and case operators in the Food class

### ISSUE THREAD

**Issue by ramasubbaiah333** [HotelManagementProjectGCIS-634TeamC/Hotel-Application#3]
Refactor the switch code smell found in the Food class

**Comment by RavitejaMali** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GCIS-634Team-C-6362c58c388aef0d65005d6b/issues/HotelManagementProjectGCIS-634TeamC/Hotel-Application/3?planning-poker) with Zenhub @Arungannon @ramasubbaiah333

**Comment by ramasubbaiah333** [comment]
Many case operators found and will take more time to refactor

**Comment by Arungannon** [comment]
It can be done in single sprint

**Comment by RavitejaMali** [comment]
Many switch cases in the Hotel class have to be cleared and that can be work in this sprint

**Comment by pakalapa** [comment]
In this I see some of the  switch case operators which might take a long time for the refactoring process.
